openapi: 3.0.1
info:
  title: monster-vampire
  x-cortex-tag: monster-vampire
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: ooze
    challenge_rating: 21
    legendary: true
    armor_class: 14
    hit_points: 218
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-vampire
      alias: github-token-test
